chores/urls.py
from django.urls import path
from . import views

app_name = 'chores'
urlpatterns = [ 
    path('',views.index, name = 'index'),
    path('login/',views.user_login, name = 'login'),
    path('logout/',views.user_logout, name = 'logout'),
    path('register/',views.register, name = 'register'),
    path('home/',views.home, name = 'home'),
    path('createhouse/', views.createhouse, name = 'createhouse'),
    path('createtask/', views.createtask, name = 'createtask'),
    path('tasks/', views.tasks, name = 'tasks'),
    path('tasks/delete/<int:task_id>', views.deletetask, name = 'deletetask'),
    path('rewards/', views.rewards, name = 'rewards'),
    path('createreward/', views.createreward, name = 'createreward'),
    path('rewards/delete/<int:reward_id>', views.deletereward, name = 'deletereward'),
    path('joinhouse/', views.joinhouse, name = 'joinhouse'),
    path('home/complete/<int:task_id>', views.completetask, name = 'completetask'),
    path('home/approve/<int:task_id>', views.approvetask, name = 'approvetask'),
    path('home/deny/<int:task_id>', views.denytask, name = 'denytask'), 
    path('home/claim/<int:reward_id>', views.claimreward, name = 'claimreward'),
    path('home/acknowledge/<int:claimed_reward_id>',views.acknowledgereward, name = 'acknowledgereward')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chores/',include('chores.urls')),
]

chores/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Household(models.Model):
    house_name = models.CharField(max_length=100)
    house_code = models.CharField(max_length=20, unique=True)

    def generate_house_code():
        import random
        char_1 = chr(random.randint(65,90))
        char_2 = chr(random.randint(65,90))
        char_3 = chr(random.randint(65,90))
        dig_1 = str(random.randint(0,9))
        dig_2 = str(random.randint(0,9))
        dig_3 = str(random.randint(0,9))

        housecode = char_1 + char_2 + char_3 + dig_1 + dig_2 + dig_3
        return housecode

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    household = models.ForeignKey('Household', on_delete=models.CASCADE)
    balance = models.PositiveIntegerField(blank=True, null=True)

class Task(models.Model):
    TASK_STATUS_CHOICES = {
        ('Incomplete', 'Incomplete'),
        ('Pending','Pending'),
        ('Complete','Complete')
    }

    household = models.ForeignKey('Household', on_delete=models.CASCADE)
    task_title = models.CharField(max_length=100)
    task_description = models.CharField(max_length = 1000, blank = True, null=True)
    task_status = models.CharField(max_length=100, choices=TASK_STATUS_CHOICES, default='Incomplete')
    date_assigned = models.DateField()
    task_reward = models.PositiveIntegerField()
    completed_by = models.ForeignKey('Person', on_delete=models.CASCADE, null= True, blank=True )

class Reward(models.Model):
    household = models.ForeignKey('Household', on_delete=models.CASCADE)
    reward_title = models.CharField(max_length=100)
    reward_description = models.CharField(max_length = 1000, blank = True, null=True)
    reward_cost = models.PositiveIntegerField()

class ClaimedReward(models.Model):
    household = models.ForeignKey('Household', on_delete=models.CASCADE)
    reward = models.ForeignKey('Reward', on_delete=models.CASCADE)
    claimed_by = models.ForeignKey('Person', on_delete=models.CASCADE)

chores/forms.py
from django import forms

ACCOUNT_CHOICES = (
    ("Parent","Parent"),
    ("Child","Child"),
)

class RegisterForm(forms.Form):
    first_name = forms.CharField(label= 'First Name', max_length=100)
    username = forms.CharField(label= 'Username', max_length=100)
    password1 = forms.CharField(label='Password',max_length=100,widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password',max_length=100,widget=forms.PasswordInput)
    account_type = forms.ChoiceField(choices = ACCOUNT_CHOICES)

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password',max_length=100,widget=forms.PasswordInput)

class TaskForm(forms.Form):
    task_title = forms.CharField(label = 'Task Title', max_length=100)
    task_description = forms.CharField(label = 'Task Description', max_length=1000, required=False)
    task_reward = forms.IntegerField(label = 'Reward')

class RewardForm(forms.Form):
    reward_title = forms.CharField(label = 'Reward Title', max_length=100)
    reward_description = forms.CharField(label = 'Reward Description',max_length = 1000, required=False)
    reward_cost = forms.IntegerField(label = 'Cost')

chores/views.py
from binascii import Incomplete
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout

from .models import Household, Person, Task, Reward, ClaimedReward
from .forms import RegisterForm, LoginForm, TaskForm, RewardForm

import datetime

# Constants

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/index.html')
    
    return home(request)

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password = password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('../home')
            else:
                context = {
                    'form' : form,
                    'error' : "Invalid login. Please try again."
                }
                return render(request,'chores/login.html', context)
    else:
        form = LoginForm()
    return render(request, 'chores/login.html', {'form' : form})

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('../')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            username = form.cleaned_data.get("username")
            password1 = form.cleaned_data.get("password1")
            password2 =form.cleaned_data.get("password2")
            account_type = form.cleaned_data.get("account_type")
            try:
                user = User.objects.get(username = username)
                context = {
                    'form' : form,
                    'error' : "The username you have entered already exists. Please try again."
                }
                return render(request,'chores/register.html', context) 
            except User.DoesNotExist:
                if password1 != password2:
                    context = {
                        'form' : form,
                        'error' : "Passwords do not match."
                    }
                    return render(request,'chores/register.html', context) 
                else:
                    user = User.objects.create_user(username = username, email = None, password = password1)
                    user.first_name = first_name
                    user.save()
                    account_group = Group.objects.get(name = account_type)
                    account_group.user_set.add(user)
                    
                    return HttpResponseRedirect('../login')
    else:
        form = RegisterForm()
    return render(request,'chores/register.html', {'form' : form})

def home(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')
    current_user = request.user

    try:
        person = Person.objects.get(pk = current_user.id)
        has_household = True

        assigned_tasks = Task.objects.filter(household = person.household)
        rewards = Reward.objects.filter(household = person.household)
        claimed_rewards = ClaimedReward.objects.filter(household = person.household)



        context = {
            'user_name' : current_user.first_name,
            'has_household' : has_household,
            'household_name' : person.household.house_name,
            'tasks' : assigned_tasks,
            'house_code' : person.household.house_code,
            'rewards' : rewards,
            'balance' : person.balance,
            'claimed_rewards' : claimed_rewards
        }

    except Person.DoesNotExist:
        has_household = False

        context = {
            'user_name' : current_user.first_name,
            'has_household' : has_household
        }
    
    if current_user.groups.filter(name = 'Parent'):
        return render(request, 'chores/home_parent.html', context)
    elif current_user.groups.filter(name = 'Child'):
        return render(request, 'chores/home_child.html', context)

def createhouse(request):

    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')
    
    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
        return home(request)
    except Person.DoesNotExist:
        pass

    temp_code = Household.generate_house_code()

    if request.method == 'POST':
        house_name = request.POST['house_name']
        
        unique_code = False
        while unique_code == False:
            try:
                existing_house = Household.objects.get(house_code = temp_code)
            except Household.DoesNotExist:
                unique_code = True
        
        new_house = Household(house_name = house_name, house_code = temp_code)
        new_house.save()

        new_person = Person(request.user.id, new_house.id)
        new_person.save()
        
        return HttpResponseRedirect('../home')

    return render(request, 'chores/household_creation.html')

def createtask(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')

    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
    except Person.DoesNotExist:
        return home(request)
    
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task_title = form.cleaned_data.get('task_title')
            task_description = form.cleaned_data.get('task_description')
            task_reward = form.cleaned_data.get('task_reward')

            if(task_reward < 0):
                context = {
                    'form' : form,
                    'error' : 'Reward cannot be negative.',
                }
                return render(request, 'chores/task_creation.html', context)  
            else:
                household = person.household
                current_date = datetime.date.today()

                new_task = Task(
                    household = household,
                    task_title = task_title,
                    task_description = task_description,
                    date_assigned = current_date,
                    task_reward = task_reward
                )
                new_task.save()
                return HttpResponseRedirect('../home')

    else:
        form = TaskForm()

    return render(request, 'chores/task_creation.html', {'form':form}) 

def tasks(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')

    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
    except Person.DoesNotExist:
        return home(request)

    house_tasks = Task.objects.filter(household = person.household)

    context = {
        'tasks' : house_tasks, 
    }
    
    return render(request, 'chores/tasks.html', context)

def deletetask(request, task_id):
    #TODO: restrict access to this so only the parent of the household can delete the task

    Task.objects.filter(pk = task_id).delete()

    
    return HttpResponseRedirect('../')

def rewards(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')

    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
    except Person.DoesNotExist:
        return home(request)

    house_rewards = Reward.objects.filter(household = person.household)

    context = {
        'rewards' : house_rewards, 
    }
    return render(request, 'chores/rewards.html', context)

def createreward(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')

    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
    except Person.DoesNotExist:
        return home(request)
    
    if request.method == 'POST':
        form = RewardForm(request.POST)
        if form.is_valid():
            reward_title = form.cleaned_data.get('reward_title')
            reward_description = form.cleaned_data.get('reward_description')
            reward_cost = form.cleaned_data.get('reward_cost')

            if(reward_cost < 0):
                context = {
                    'form' : form,
                    'error' : 'Cost cannot be negative.',
                }
                return render(request, 'chores/rewards_creation.html', context)  
            else:
                household = person.household

                new_reward = Reward(
                    household = household,
                    reward_title = reward_title,
                    reward_description = reward_description,
                    reward_cost = reward_cost
                )

                new_reward.save()
                return HttpResponseRedirect('../home')

    else:
        form = RewardForm()

    return render(request, 'chores/rewards_creation.html', {'form' : form})

def deletereward(request, reward_id):
    #TODO: restrict access to this so only the parent of the household can delete the reward

    Reward.objects.filter(pk = reward_id).delete()

    
    return HttpResponseRedirect('../')

def joinhouse(request):
    if not request.user.is_authenticated:
        return render(request, 'chores/login_error.html')
    
    current_user = request.user
    try:
        person = Person.objects.get(pk = current_user.id)
        return home(request)
    except Person.DoesNotExist:
        pass
    
    if request.method == 'POST':
        house_code = request.POST['house_code']

        try:

chores/templates/chores/home_child.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Home</title>
</head>

<body>
    <header>
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
            <li><a href="{% url 'chores:logout' %}">Logout</a></li>
        </ul>
    </header>

    <p>Viewing Child Dashboard</p>
    
    <h5>Welcome, {{user_name}}</h5>

    {% if has_household %}
    <h1>{{household_name}} Household</h1>
    <h3>Total Coins: {{balance}}</h3>

    <div class="div-body">
        <div class="div-head">
            <h5>Incomplete Tasks</h5>
        </div>

        {% for task in tasks %}
            {% if task.task_status == 'Incomplete'%}
            <div class = "div-content" style="display: flex">
                <div class="left-div">
                    <h5>{{task.task_title}}</h5>
                    <p class = "task-desc">{{task.task_description}}</p>
                    <p>Reward: {{task.task_reward}}</p>
                </div>

                <div class = "right-div">
                    <a href="complete/{{task.id}}"><img src="{% static 'chores/images/complete_icon.png' %}" alt="" style="width: 20px; height: auto"></a>
                </div>
            </div>
            {% endif %}
        {% endfor %}

        <div class = "div-footer"></div>
    </div>

    <div class="div-body">
        <div class="div-head">
            <h5>Available Rewards</h5>
        </div>

        {% for reward in rewards %}
            <div class = "div-content" style="display: flex">
                <div class="left-div">
                    <h5>{{reward.reward_title}}</h5>
                    <p class = "task-desc">{{reward.reward_description}}</p>
                    <p>Cost: {{reward.reward_cost}}</p>
                </div>

                {% if balance >= reward.reward_cost %}
                <div class="right-div">
                    <a href="claim/{{reward.id}}"><img src="{% static 'chores/images/reward_icon.png' %}" alt="" style="width: 20px; height: auto"></a>
                </div>
                {% endif %}
            </div>
            
        {% endfor %}

        <div class = "div-footer"></div>
    </div>

    {% else %}
    <p>To start using CHORES enter a house code to join a Household!</p>
    <form action="{% url 'chores:joinhouse' %}"  method="post">
        {% csrf_token %}
        <p>{{error}}</p>
        <label for="house_code">House Code:</label>
        <input type="text" name="house_code" id="house_code">
        <input class= "button-3d" type="submit" value="Join House">
    </form>
    {% endif %}

</body>

chores/templates/chores/home_parent.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Home</title>
</head>
<body>
    <header>
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
            <li><button id="open-sidebar" onclick="sidebar_open()"><img src="{% static 'chores/images/expand_icon.png' %}" style="width: 20px; height: auto"></button></li>
            <li><button id="close-sidebar" onclick="sidebar_close()" style="display: none"><img src="{% static 'chores/images/expand_icon.png' %}" style="width: 20px; height: auto"></button></li>
            <li><a href="{% url 'chores:logout' %}">Logout</a></li>
        </ul>
    </header>

    <div class = "side-bar" id = "mySidebar" style="display: none">
        <h3>Quick Menu</h3>
        <ul>
            <li><a href="{% url 'chores:createtask' %}">Create Tasks</a></li>
            <li><a href="{% url 'chores:tasks' %}">Manage Tasks</a></li>
            <li><a href="{% url 'chores:createreward' %}">Create Rewards</a></li>
            <li><a href="{% url 'chores:rewards' %}">Manage Rewards</a></li>
        </ul>
    </div>

    <div id = "main">

    <p>Viewing Parent Dashboard</p>
    
    <h5>Welcome, {{user_name}}</h5>
    {% if has_household %}
    <h1>{{household_name}} Household</h1>
    <h3>House Code: {{house_code}}</h3>

    <div class="div-body">
        <div class="div-head">
            <h5>Completed Tasks</h5>
        </div>

        {% for task in tasks %}
            {% if task.task_status == 'Pending'%}
            <div class = "div-content" style="display: flex">
                <div class = "left-div">
                    <h5>{{task.task_title}}</h5>
                    <p class = "task-desc">{{task.task_description}}</p>
                    <p>Reward: {{task.task_reward}}</p>
                    <p>Completed By: {{task.completed_by.user.first_name}}</p>
                </div>

                <div class = "right-div">
                    <a href="approve/{{task.id}}"><img src="{% static 'chores/images/complete_icon.png' %}" alt="" style="width: 20px; height: auto"></a>
                    <a href="deny/{{task.id}}"><img src="{% static 'chores/images/decline_icon.png' %}" alt="" style="width: 20px; height: auto"></a>

                </div>
            </div>
            {% endif %}
        {% endfor %}

        <div class = "div-footer"></div>
    </div>
    
    <div class="div-body">
        <div class="div-head">
            <h5>Incomplete Tasks</h5>
        </div>

        {% for task in tasks %}
            {% if task.task_status == 'Incomplete'%}
            <div class = "div-content">
                <h5>{{task.task_title}}</h5>
                <p class = "task-desc">{{task.task_description}}</p>
                <p>Reward: {{task.task_reward}}</p>
            </div>
            {% endif %}
        {% endfor %}

        <div class = "div-footer"></div>
    </div>

    <div class="div-body">
        <div class="div-head">
            <h5>Redeemed Rewards</h5>
        </div>

        {% for claimed_reward in claimed_rewards %}
        <div class = "div-content" style="display: flex">
            <div class = 'left-div'>
                <h5>{{claimed_reward.reward.reward_title}}</h5>
                <p>Claimed By: {{claimed_reward.claimed_by.user.first_name}}</p>
            </div>

            <div class = 'right-div'>
                <a href="acknowledge/{{claimed_reward.id}}"><img src="{% static 'chores/images/complete_icon.png' %}" alt="" style="width: 20px; height: auto"></a>
            </div>
        </div>
        {% endfor %}

        <div class = "div-footer"></div>
    </div>


    </div>


    {% else %}
        <p>To start using CHORES create a Household below!</p>
        <a class = "button-3d" href="{% url 'chores:createhouse' %}">Create Household</a>
    {% endif %}


<script>
    function sidebar_open() {
        document.getElementById("main").style.marginRight = "25%";
        document.getElementById("mySidebar").style.width = "25%";
        document.getElementById("mySidebar").style.marginLeft = "75%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("open-sidebar").style.display = "none";
        document.getElementById("close-sidebar").style.display = "block";


    }
    
    function sidebar_close() {
        document.getElementById("main").style.marginRight = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("close-sidebar").style.display = "none";
        document.getElementById("open-sidebar").style.display = "block";

    }

</script>

</body>

chores/templates/chores/household_creation.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_form.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Household Creation</title>
</head>


<body>

    <div class="heading">
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
        </ul>
    </div>

    <div class = "registration">
        <h1>Create a Household</h1>
        <form action="{% url 'chores:createhouse' %}" method="post">
            {% csrf_token %}
            <label for="house_name">House Name: </label>
            <input id = "house_name" type="text" name = "house_name">
            <input type="submit" value="Create Household">
        </form>
    </div>
    
</body>
</html>

chores/templates/chores/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES</title>
    </head>
    <body>
        <header>
            <h1>CHORES</h1>
            <p>Making chores fun again.</p>
        </header>

        <div class="account">
            <ul>
                <li><a href="{% url 'chores:login' %}" class="button-3d">Login</a></li>
                <li><a href="{% url 'chores:register' %}" class="button-3d">Create Account</a></li>
            </ul>
        </div>
    </body>
</html>

chores/templates/chores/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_form.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Login</title>
</head>

    <body>

        <div class="heading">
            <ul>
                <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
            </ul>
        </div>


        <div class = "registration">
            <h1>Login</h1>
            <span class ="error-message">{{error}}</span>
            <form action="{% url 'chores:login' %}" method = "post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Login">
            </form>
            
        </div>
    </body>
</html>

chores/templates/chores/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_form.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Create Account</title>
</head>
<body>
    <div class="heading">
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
        </ul>
    </div>
    <div class="registration">
        <h1>Create Your Account</h1>
        <span class="error-message">{{error}}</span>
        <form action="{% url 'chores:register' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create Account">
        </form>
    </div>
</body>
</html>

chores/templates/chores/rewards.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Rewards</title>
</head>
<body>
    <header>
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
            <li><a href="{% url 'chores:logout' %}">Logout</a></li>
        </ul>
    </header>

    <h1>Rewards</h1>

    <div class="div-body">
        {% for reward in rewards %}
        <div class = "div-content" style="display: flex">
            <div class = "left-div">
                <h5>{{reward.reward_title}}</h5>
                <p class = "task-desc">{{reward.reward_description}}</p>
                <p>Cost: {{reward.reward_cost}}</p>
            </div>
            <div class = "right-div">
                <a href="delete/{{reward.id}}"><img src="{% static 'chores/images/delete_icon.png' %}" alt="" style="width: 20px; height: auto"></a>
            </div>
        </div>
        {% endfor %}


    </div>


</body>
        
    

chores/templates/chores/rewards_creation.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_form.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Reward Creation</title>
</head>

<body>
    <div class="heading">
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
        </ul>
    </div>


    <div class = "registration">
        <h1>Reward Creation</h1>
        <span class = "error-message">{{error}}</span>
        <form action="{% url 'chores:createreward' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value = "Create Reward">
        </form>
    </div>
    
    
</body>
</html>

chores/templates/chores/task_creation.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'chores/style_form.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHORES - Task Creation</title>
</head>

<body>
    <div class="heading">
        <ul>
            <li style="float:left"><a href="{% url 'chores:index' %}">CHORES</a></li>
        </ul>
    </div>


    <div class = "registration">
        <h1>Task Creation</h1>
        <span class = "error-message">{{error}}</span>
        <form action="{% url 'chores:createtask' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value = "Create Task">
        </form>
    </div>
    
    
</body>
</html>